config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  get '/', to: 'breweries#index'
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to:'ratings#new'
  #post 'ratings', to: 'ratings#create'
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :beers
  resources :breweries
  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  # config/routes.rb
  get '/signout', to: 'sessions#destroy', as: 'signout'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/beer.rb
class Beer < ApplicationRecord
  include RatingAverage
  belongs_to :brewery
  has_many :ratings, dependent: :destroy
  has_many :raters, through: :ratings, source: :user
  validates :name, presence: true, allow_blank: false
  def average
    if ratings.count == 0
      return 0
    end

    ratings.map(&:score).sum / ratings.count.to_f
  end

  def to_s
    "#{name} by #{brewery.name}"
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: %i[show edit update destroy]

  # GET /beers or /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1 or /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
    @brewery = Brewery.all
    @styles = ["Weizen", "Lager", "Pale ale", "IPA", "Porter", "Lowalcohol"]
  end

  # GET /beers/1/edit
  def edit
    @breweries = Brewery.all
    @styles = ["Weizen", "Lager", "Pale ale", "IPA", "Porter", "Lowalcohol"]
  end

  # POST /beers or /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beers_path, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        @breweries = Brewery.all
        @styles = ["Weizen", "Lager", "Pale ale", "IPA", "Porter", "Lowalcohol"]
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1 or /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to beer_url(@beer), notice: "Beer was successfully updated." }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1 or /beers/1.json
  def destroy
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url, notice: "Beer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer
    @beer = Beer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_params
    params.require(:beer).permit(:name, :style, :brewery_id)
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_beer.html.erb
<div id="<%= dom_id beer %>">
  <p>
    <strong>Name:</strong>
    <%= link_to beer.name, beer %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= beer.style %>
  </p>

  <p>
    <strong>Brewery:</strong>
    <%=link_to beer.brewery.name, beer.brewery %>
  </p>

</div>

app/views/beers/_form.html.erb
<%= form_with(model: beer) do |form| %>
  <% if beer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
        <% beer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.label :brewery_id, style: "display: block" %>
    <%= form.number_field :brewery_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render "form", beer: @beer %>

<br>

<div>
  <%= link_to "Show this beer", @beer %> |
  <%= link_to "Back to beers", beers_path %>
</div>

app/views/beers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Beers</h1>

<%= link_to 'List of breweries', breweries_path %>
<div id="beers">
  <% @beers.each do |beer| %>
    <%= render beer %>
  <% end %>
</div>

<%= link_to "New beer", new_beer_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= form_for(@beer) do |f| %>
<div>
  Name: &nbsp &nbsp <%= f.text_field :name %>
<div>
  Style:&nbsp &nbsp &nbsp <%= f.select :style, options_for_select(@styles) %>
<div>
  Brewery:<%= f.select :brewery_id, options_from_collection_for_select(@brewery, :id, :name) %>
<div>
<br>
  <%= f.submit %>
<% end %>

<br>
<br>

<div>
  <%= link_to "Back to beers", beers_path %>
</div>

app/views/beers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @beer %>


<div>
  <% if @beer.ratings.empty? %>
  beer has not yet been rated!
  <% else %>
  beer has <%= @beer.ratings.count%> <%="rating".pluralize(@beer.ratings.count)%> with an average of <%=@beer.average_rating %>
  <% end %>
  <p>
  <%= link_to "Edit this beer", edit_beer_path(@beer) %>
  <%= link_to "Back to beers", beers_path %>

  <%= button_to "Destroy this beer", @beer, method: :delete %>
</div>