config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  get '/', to: 'breweries#index'
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to:'ratings#new'
  #post 'ratings', to: 'ratings#create'
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :beers
  resources :breweries
  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  # config/routes.rb
  get '/signout', to: 'sessions#destroy', as: 'signout'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="navibar">
    <%= link_to 'Breweries|', breweries_path %>
    <%= link_to 'Beers|', beers_path %>
    <%= link_to 'Beer clubs|', beer_clubs_path %>
    <%=link_to "Ratings|", ratings_path %>
    <%=link_to "Users", users_path %>
    <hr>
    <% if current_user %> <%= link_to(current_user.username, current_user) %> <%=link_to "|Rate a new beer|", new_rating_path %>
    <%=link_to "|Join a club|", new_membership_path %> 
    <%=link_to "|Sign out|", signout_path %>
      <% else %>
          <%= link_to("Sign up", signup_path) %> <%= link_to("Sign in", signin_path) %> <% end %>
    
  </div>

  <%= yield %>

</body>
</html>